apiVersion: v1
kind: Namespace
metadata:
  name: __SERVICE_NAME__
  labels:
    platform.example.io/owner: __OWNER_TEAM__
    platform.example.io/environment: dev
    platform.example.io/criticality: tier-2
