apiVersion: v1
kind: Service
metadata:
  name: payments-api
  labels:
    app.kubernetes.io/name: payments-api
    platform.example.io/owner: payments-team
    platform.example.io/environment: dev
    platform.example.io/criticality: tier-2
spec:
  selector:
    app.kubernetes.io/name: payments-api
  ports:
    - name: http
      port: 80
      targetPort: http
